name: Generate Content

on:
  workflow_dispatch:
    inputs:
      task_type:
        description: 'Jenis konten yang akan di-generate'
        required: true
        default: 'article'
        type: choice
        options:
          - article
          - calculator_tool
      topic_id:
        description: 'ID topik spesifik (kosongkan untuk ambil dari queue)'
        required: false
        type: string

  repository_dispatch:
    types: [run-task]

  schedule:
    # Artikel: setiap 2 hari jam 02:00 UTC (09:00 WIB)
    - cron: '0 2 */2 * *'
    # Tools: tanggal 1 dan 15 setiap bulan jam 06:00 UTC
    - cron: '0 6 1,15 * *'

jobs:
  generate-article:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: |
      (github.event_name == 'schedule' && github.event.schedule == '0 2 */2 * *') ||
      (github.event_name == 'repository_dispatch' && github.event.client_payload.task_type == 'article') ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.task_type == 'article')

    steps:
      - name: Checkout ai-engine
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set task type artikel
        run: |
          echo "TASK_TYPE=article" >> \$GITHUB_ENV
          echo "TOPIC_ID=\${{ github.event.inputs.topic_id || github.event.client_payload.topic_id_override || '' }}" >> \$GITHUB_ENV

      - name: Jalankan Pipeline
        env:
          BRAIN_PAT:     \${{ secrets.BRAIN_PAT }}
          CF_ACCOUNT_ID: \${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN:  \${{ secrets.CF_API_TOKEN }}
          GITHUB_TOKEN:  \${{ secrets.GITHUB_TOKEN }}
          ENGINE_REPO:   \${{ github.repository }}
          BRAIN_REPO:    akunTools/ai-brain
        run: python scripts/run_pipeline.py

      - name: Kirim email notifikasi gagal
        if: failure()
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp-relay.brevo.com
          server_port: 587
          secure: false
          username: \${{ secrets.BREVO_USERNAME }}
          password: \${{ secrets.BREVO_PASSWORD }}
          subject: '[AI Engine] Pipeline Failed — article'
          to: \${{ secrets.NOTIFICATION_EMAIL }}
          from: AI Engine <\${{ secrets.GMAIL_USERNAME }}>
          body: |
            Pipeline failed.

            Task type : article
            Run ID    : \${{ github.run_id }}

            Check Actions tab for details:
            https://github.com/\${{ github.repository }}/actions/runs/\${{ github.run_id }}

      - name: Kirim email notifikasi queue kosong
        if: success() && hashFiles('/tmp/queue_empty.flag') != ''
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp-relay.brevo.com
          server_port: 587
          secure: false
          username: \${{ secrets.BREVO_USERNAME }}
          password: \${{ secrets.BREVO_PASSWORD }}
          subject: '[AI Engine] Queue Empty — Action Required'
          to: \${{ secrets.NOTIFICATION_EMAIL }}
          from: AI Engine <\${{ secrets.GMAIL_USERNAME }}>
          body: |
            The topic queue is now empty.
            Add new topics via webhook command add_topic.

      - name: Update sitemap setelah publish berhasil
        if: success() && hashFiles('/tmp/queue_empty.flag') == ''
        env:
          GITHUB_TOKEN:  \${{ secrets.GITHUB_TOKEN }}
          ENGINE_REPO:   \${{ github.repository }}
          SITE_BASE_URL: https://saas.blogtrick.eu.org
        run: python scripts/sitemap_gen.py

  generate-tool:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: |
      (github.event_name == 'schedule' && github.event.schedule == '0 6 1,15 * *') ||
      (github.event_name == 'repository_dispatch' && github.event.client_payload.task_type == 'calculator_tool') ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.task_type == 'calculator_tool')

    steps:
      - name: Checkout ai-engine
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set task type tools
        run: |
          echo "TASK_TYPE=calculator_tool" >> \$GITHUB_ENV
          echo "TOPIC_ID=\${{ github.event.inputs.topic_id || github.event.client_payload.topic_id_override || '' }}" >> \$GITHUB_ENV

      - name: Jalankan Pipeline
        env:
          BRAIN_PAT:     \${{ secrets.BRAIN_PAT }}
          CF_ACCOUNT_ID: \${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN:  \${{ secrets.CF_API_TOKEN }}
          GITHUB_TOKEN:  \${{ secrets.GITHUB_TOKEN }}
          ENGINE_REPO:   \${{ github.repository }}
          BRAIN_REPO:    akunTools/ai-brain
        run: python scripts/run_pipeline.py

      - name: Kirim email notifikasi gagal
        if: failure()
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp-relay.brevo.com
          server_port: 587
          secure: false
          username: \${{ secrets.BREVO_USERNAME }}
          password: \${{ secrets.BREVO_PASSWORD }}
          subject: '[AI Engine] Pipeline Failed — calculator_tool'
          to: \${{ secrets.NOTIFICATION_EMAIL }}
          from: AI Engine <\${{ secrets.GMAIL_USERNAME }}>
          body: |
            Pipeline failed.

            Task type : calculator_tool
            Run ID    : \${{ github.run_id }}

            Check Actions tab for details:
            https://github.com/\${{ github.repository }}/actions/runs/\${{ github.run_id }}

      - name: Kirim email notifikasi queue kosong
        if: success() && hashFiles('/tmp/queue_empty.flag') != ''
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp-relay.brevo.com
          server_port: 587
          secure: false
          username: \${{ secrets.BREVO_USERNAME }}
          password: \${{ secrets.BREVO_PASSWORD }}
          subject: '[AI Engine] Tool Queue Empty — Action Required'
          to: \${{ secrets.NOTIFICATION_EMAIL }}
          from: AI Engine <\${{ secrets.GMAIL_USERNAME }}>
          body: |
            The calculator tool queue is now empty.
            Add new topics via webhook command add_topic
            with task_type: calculator_tool.

      - name: Update sitemap setelah publish berhasil
        if: success() && hashFiles('/tmp/queue_empty.flag') == ''
        env:
          GITHUB_TOKEN:  \${{ secrets.GITHUB_TOKEN }}
          ENGINE_REPO:   \${{ github.repository }}
          SITE_BASE_URL: https://saas.blogtrick.eu.org
        run: python scripts/sitemap_gen.py
