"""
reporter.py
Generate laporan harian dan simpan ke ai-brain/logs/reports/.
Output teks laporan juga disimpan ke /tmp/daily_report.txt
untuk digunakan oleh workflow saat kirim email.
"""
import os
import sys
import json
from datetime import datetime, timedelta

sys.path.insert(0, os.path.dirname(__file__))
from loader import fetch_file, update_file


def run():
    # Laporan untuk kemarin
    yesterday = (datetime.utcnow() - timedelta(days=1))
    date_str  = yesterday.strftime("%Y-%m-%d")

    success_count = 0
    failure_entries = []

    # Baca log sukses
    try:
        d = json.loads(fetch_file(f"logs/success/{date_str}.json"))
        success_count = len(d.get("entries", []))
    except Exception:
        pass

    # Baca log failure
    try:
        d = json.loads(fetch_file(f"logs/failures/{date_str}.json"))
        failure_entries = d.get("entries", [])
    except Exception:
        pass

    total = success_count + len(failure_entries)
    rate  = round(success_count / max(total, 1) * 100)

    # Cek queue
    queue_info = "unknown"
    try:
        s = json.loads(fetch_file("config/schedule.json"))
        pending = sum(
            1 for t in s["topic_queue"] if t["status"] == "pending"
        )
        queue_info = f"{pending} topics pending"
        if pending == 0:
            queue_info = "0 topics pending — ACTION REQUIRED"
    except Exception:
        pass

    # Format laporan
    failure_lines = "\n".join([
        f"- {e['topic_id']}: {e.get('result', {}).get('issues', [])}"
        for e in failure_entries
    ]) or "None"

    report = f"""# Daily Report — {date_str}

## Summary
- Success : {success_count}
- Failed  : {len(failure_entries)}
- Rate    : {rate}%
- Queue   : {queue_info}

## Failed Items
{failure_lines}

## Action Required
{"Review failures. Use retry_failed webhook after fixing the issue." if failure_entries else "None — system is healthy."}
{"QUEUE IS EMPTY. Add new topics via webhook add_topic command." if "0 topics" in queue_info else ""}

---
Generated by ai-engine reporter at {datetime.utcnow().isoformat()}
"""

    # Simpan ke ai-brain
    update_file(
        f"logs/reports/{date_str}-daily.md",
        report,
        f"[reporter] Daily report {date_str}"
    )

    # Simpan ke /tmp untuk dipakai workflow saat kirim email
    with open("/tmp/daily_report.txt", "w") as f:
        f.write(report)

    # Buat flag jika ada failure untuk trigger alert email terpisah
    if failure_entries:
        with open("/tmp/has_failures.flag", "w") as f:
            f.write(str(len(failure_entries)))

    print(report)


if __name__ == "__main__":
    run()
